matrix:
  include:
    - os: linux
      language: c
      dist: xenial
    - os: osx
      osx_image: xcode8.3
      language: objective-c

script:
  - . ./.travis/build.sh
        
branches:
  only:
    - master

compiler:
  - gcc

